import type { Metadata } from "next";
import { Jersey_10, Space_Mono } from "next/font/google";
import "./globals.css";
import SpaceBackground from "../components/SpaceBackground";

const jersey10 = Jersey_10({
  variable: "--font-jersey",
  weight: "400",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jersey10.variable} ${spaceMono.variable} antialiased`}
      >
        <SpaceBackground />
        {children}
      </body>
    </html>
  );
}
